title: Producten
fields:
  -
    handle: product
    field:
      collapse: false
      previews: true
      fullscreen: true
      sets:
        new_set_group:
          display: 'New Set Group'
          instructions: null
          icon: null
          sets:
            product:
              display: Product
              instructions: null
              icon: null
              fields:
                -
                  handle: text
                  field:
                    restrict: false
                    buttons:
                      - bold
                      - italic
                      - unorderedlist
                      - orderedlist
                      - quote
                      - link
                      - image
                      - table
                    automatic_line_breaks: true
                    automatic_links: false
                    escape_markup: false
                    heading_anchors: false
                    smartypants: false
                    table_of_contents: false
                    antlers: false
                    type: markdown
                    display: Text
                    icon: markdown
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    hide_display: false
      type: replicator
      display: Product
      icon: replicator
      listable: hidden
      instructions_position: above
      visibility: visible
      hide_display: false
      replicator_preview: true
